name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_DEV_PASSWORD }}" | docker login terraacr2025prod.azurecr.io -u ${{ secrets.ACR_DEV_USERNAME }} --password-stdin

      - name: Fetch latest tag
        id: get_version
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          [[ -z "$LATEST_TAG" ]] && LATEST_TAG="v0.0.0"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Increment version
        id: versioning
        run: |
          VERSION=$LATEST_TAG
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Version updated to: $NEW_VERSION"

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_DEV_USERNAME }}/myapp:$NEW_VERSION .
          docker push ${{ secrets.ACR_DEV_USERNAME }}/myapp:$NEW_VERSION

      - name: Clone Flux GitOps repository
        run: |
          git clone https://github.com/charungooa/flux-gitops02.git flux-repo
          cd flux-repo
          sed -i "s|image: ${{ secrets.ACR_DEV_USERNAME }}/myapp:.*|image: ${{ secrets.ACR_DEV_USERNAME }}/myapp:$NEW_VERSION|" dev/deployment.yaml

      - name: Commit and push updated image version to Flux GitOps repository
        run: |
          cd flux-repo
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dev/deployment.yaml
          git commit -m "Updated image to $NEW_VERSION"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/flux-gitops02.git

      - name: Tag and push new version to mypy-app-repo
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $NEW_VERSION
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/mypy-app-repo.git
          git push origin $NEW_VERSION