name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_DEV_PASSWORD }}" | docker login terraacr2025dev.azurecr.io -u ${{ secrets.ACR_DEV_USERNAME }} --password-stdin

      - name: Fetch latest tag from ACR and increment version
        id: versioning
        run: |
          # Get the latest tag from Azure Container Registry
          LATEST_TAG=$(az acr repository show-tags --name terraacr2025dev --repository myapp --orderby time_desc --output tsv | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          
          # Debugging: Print the fetched tag
          echo "Latest tag from ACR: $LATEST_TAG"

          # Set default if no tag found
          [[ -z "$LATEST_TAG" ]] && LATEST_TAG="v0.0.0"

          # Extract version numbers using regex
          MAJOR=$(echo $LATEST_TAG | grep -oP '(?<=v)[0-9]+' || echo "0")
          MINOR=$(echo $LATEST_TAG | grep -oP '(?<=v[0-9]+\.)[0-9]+' || echo "0")
          PATCH=$(echo $LATEST_TAG | grep -oP '(?<=v[0-9]+\.[0-9]+\.)[0-9]+' || echo "0")

          # Increment PATCH version
          NEW_PATCH=$((PATCH + 1))

          # Generate new image tag
          IMAGE_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"

          # Debugging: Print the new image tag
          echo "New image tag: $IMAGE_TAG"

          # Store in GitHub environment variables
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t terraacr2025dev.azurecr.io/myapp:$IMAGE_TAG .
          docker push terraacr2025dev.azurecr.io/myapp:$IMAGE_TAG

      - name: Clone and update Flux GitOps repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/flux-gitops02.git flux-repo
          cd flux-repo
          sed -i "s|image: terraacr2025dev.azurecr.io/myapp:.*|image: terraacr2025dev.azurecr.io/myapp:$IMAGE_TAG|" dev/deployment.yaml

      - name: Commit and push updated image version to Flux GitOps repository
        run: |
          cd flux-repo
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dev/deployment.yaml
          git commit -m "Updated image to $IMAGE_TAG" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/flux-gitops02.git || echo "No changes to push"