name: Dev Build and Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all tags are fetched

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_DEV_PASSWORD }}" | docker login terraacr2025dev.azurecr.io -u ${{ secrets.ACR_DEV_USERNAME }} --password-stdin

      - name: Get Latest Version Tag
        id: get_version
        run: |
          git fetch --tags  # Ensure all tags are fetched
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          if [[ -z "$LATEST_TAG" ]]; then
            LATEST_TAG="v0.0.0"
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag detected: $LATEST_TAG"

      - name: Increment Version (PATCH)
        id: versioning
        run: |
          # Extract MAJOR, MINOR, PATCH
          VERSION=${{ env.LATEST_TAG }}
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # Increment PATCH version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New semantic version: $NEW_VERSION"

      - name: Handle PR Versioning
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          NEW_VERSION="${{ env.NEW_VERSION }}-PR${PR_NUMBER}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Updated PR Version: $NEW_VERSION"

      - name: Build and Push Docker Image to ACR
        run: |
          docker build -t terraacr2025dev.azurecr.io/myapp:${{ env.NEW_VERSION }} .
          docker push terraacr2025dev.azurecr.io/myapp:${{ env.NEW_VERSION }}

      - name: Update FluxCD GitOps Repository with New Image Tag
        run: |
          git clone https://github.com/charungooa/flux-gitops02.git
          cd flux-gitops02

          # Update deployment.yaml with the new image tag
          sed -i 's|image: terraacr2025dev.azurecr.io/myapp:.*|image: terraacr2025dev.azurecr.io/myapp:${{ env.NEW_VERSION }}|' dev/deployment.yaml

          # Commit and Push Changes
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dev/deployment.yaml
          git commit -m "Update image to ${{ env.NEW_VERSION }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/flux-gitops02.git

      - name: Create Git Tag for New Version
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}