name: Prod Build and Deploy

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Provide GH_TOKEN for 'gh' CLI authentication
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Only run if we're on the 'main' branch
    if: github.ref == 'refs/heads/main'

    steps:
      #
      # 1) Check out source code
      #
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #
      # 2) (Optional) Azure CLI Login
      #
      # If you need to use 'az acr repository show-tags' (like we do below),
      # you must log into Azure CLI and the ACR. If you already have enough
      # permissions with just Docker login, you can skip or adjust this.
      #
      - name: Azure CLI Login
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_CLIENT_ID }}" \
            -p "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"
      
      # - name: Log in to Azure Container Registry (Staging)
      #   run: |
      #     echo ${{ secrets.ACR_STAGE_PASSWORD }} | docker login terraacr2025prod.azurecr.io \
      #       -u ${{ secrets.ACR_STAGE_USERNAME }} --password-stdin
      #     az acr login --name terraacr2025prod
      #     echo "Logging into ACR (terraacr2025prod)..."
      #     az acr login --name terraacr2025prod || echo "Could not ACR login via az CLI."

      #
      # 3) Docker login to Production ACR
      #
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PROD_PASSWORD }}" | docker login terraacr2025prod.azurecr.io \
            -u "${{ secrets.ACR_PROD_USERNAME }}" --password-stdin

      #
      # 4) Determine Version Type (major/minor/patch)
      #    by parsing merge commit & PR labels
      #
      - name: Determine Version Type
        id: version_type
        run: |
          VERSION_TYPE="patch"  # default

          # 1) Get the most recent commit message on 'main'
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Latest commit message:"
          echo "$COMMIT_MSG"

          # 2) Extract PR number from lines like "Merge pull request #NN from ..."
          PR_NUMBER=$(echo "$COMMIT_MSG" \
            | grep -oE 'Merge pull request #[0-9]+' \
            | grep -oE '[0-9]+' || true)

          if [ -n "$PR_NUMBER" ]; then
            echo "Detected a merged PR #$PR_NUMBER. Checking labels with gh CLI..."
            PR_LABELS=$(gh pr view "$PR_NUMBER" --json labels -q '.labels[].name' || true)
            echo "PR Labels: $PR_LABELS"

            # Check for "major" or "minor" (case-insensitive) in labels
            if echo "$PR_LABELS" | grep -qi "major"; then
              VERSION_TYPE="major"
            elif echo "$PR_LABELS" | grep -qi "minor"; then
              VERSION_TYPE="minor"
            else
              # Optionally check commit for special keywords
              if [[ "$COMMIT_MSG" == *"BREAKING CHANGE"* ]]; then
                VERSION_TYPE="major"
              elif [[ "$COMMIT_MSG" == *"feat:"* ]]; then
                VERSION_TYPE="minor"
              fi
            fi
          else
            echo "No merged PR reference found in commit message. Defaulting to patch..."
            # Optionally check commit for keywords
            if [[ "$COMMIT_MSG" == *"BREAKING CHANGE"* ]]; then
              VERSION_TYPE="major"
            elif [[ "$COMMIT_MSG" == *"feat:"* ]]; then
              VERSION_TYPE="minor"
            fi
          fi

          echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_ENV
          echo "Version Type: $VERSION_TYPE"

      #
      # 5) Fetch latest vX.Y.Z tag from Production ACR & increment
      #
      - name: Fetch latest image tag from Prod ACR
        id: versioning
        run: |
          echo "=== Fetching all tags for 'myapp' in Prod ACR (debug) ==="
          az acr repository show-tags --name terraacr2025prod --repository myapp --orderby time_desc --output table || true

          echo "=== Fetching latest vX.Y.Z tag ==="
          ALL_TAGS=$(az acr repository show-tags --name terraacr2025prod \
                       --repository myapp \
                       --orderby time_desc \
                       --output tsv 2>/dev/null || true)
          LATEST_TAG=$(echo "$ALL_TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          if [ -z "$LATEST_TAG" ]; then
            echo "'myapp' repository not found or no valid tags. Starting at v0.0.0."
            LATEST_TAG="v0.0.0"
          fi

          echo "Latest tag from ACR: $LATEST_TAG"

          MAJOR=$(echo "$LATEST_TAG" | awk -F. '{print substr($1,2)}')
          MINOR=$(echo "$LATEST_TAG" | awk -F. '{print $2}')
          PATCH=$(echo "$LATEST_TAG" | awk -F. '{print $3}')

          echo "Extracted version components: MAJOR=$MAJOR, MINOR=$MINOR, PATCH=$PATCH"

          # Read VERSION_TYPE from environment
          case "${VERSION_TYPE}" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch|*)
              PATCH=$((PATCH + 1))
              ;;
          esac

          IMAGE_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW image tag (after increment) = $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      #
      # 6) Build & Push Docker Image to Production ACR
      #
      - name: Build and Push Docker Image
        run: |
          echo "Using IMAGE_TAG=$IMAGE_TAG"
          docker build -t terraacr2025prod.azurecr.io/myapp:$IMAGE_TAG .
          docker push terraacr2025prod.azurecr.io/myapp:$IMAGE_TAG

      #
      # 7) Update FluxCD GitOps Repository with New Image Tag
      #
      - name: Update FluxCD GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/flux-gitops02.git
          cd flux-gitops02

          echo "=== BEFORE SED: prod/deployment.yaml ==="
          cat prod/deployment.yaml || true

          echo "=== Updating image tag in prod/deployment.yaml ==="
          sed -i "s|^\(\s*image:\s*\)terraacr2025prod.azurecr.io/myapp:.*|\1terraacr2025prod.azurecr.io/myapp:$IMAGE_TAG|" prod/deployment.yaml

          echo "=== AFTER SED ==="
          cat prod/deployment.yaml || true

          # Commit & push changes
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add prod/deployment.yaml
          git commit -m "Update image to $IMAGE_TAG" || echo "No changes to commit."
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/charungooa/flux-gitops02.git || echo "No changes to push."